### ISSUE TITLE
repl.it website hourboost

### ISSUE THREAD

**Issue by XdekHckr** [valnssh/vaporBooster#1]
hi I want to run it on repl.it website but i need index.js main file not to run with batch file only 100% javascript so how do i do it?
Any ideas?

**Comment by valnssh** [comment]
**Hello!** Sorry for my late answer.

The reality is that I never tried repl.it, I deduce that you want to run the .js file, if that is the case you could either start it with `npm run start` or execute the `./src/hourBooster.js` file with node.
I hope I have helped you, in case of any questions do not hesitate to contact me, have a great day!
